<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Ещё две legacy-таблицы без IDENTITY на PK — transaction и client.
 * Из-за этого insertGetId в TransactionImportController падал на
 * NOT NULL id violation («ошибка создания» на всех 308 строках).
 *
 * Тот же паттерн что 000050/060/090/000030 — ALTER + setval.
 * Идемпотентно: если identity уже есть, пропускаем.
 */
return new class extends Migration
{
    public $withinTransaction = false;

    private array $tables = ['transaction', 'client'];

    public function up(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            $hasIdentity = DB::scalar(
                "SELECT count(*) FROM pg_attribute
                 WHERE attrelid = to_regclass('public.$quoted')
                   AND attname='id' AND attidentity <> ''"
            );
            if ($hasIdentity) continue;

            DB::statement("ALTER TABLE $quoted ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");

            $seqName = '"' . $t . '_id_seq"';
            $maxId = (int) DB::scalar("SELECT COALESCE(MAX(id), 0) FROM $quoted");
            $start = max(1, $maxId + 1);
            DB::statement("SELECT setval('$seqName', $start, false)");
        }
    }

    public function down(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            DB::statement("ALTER TABLE $quoted ALTER COLUMN id DROP IDENTITY IF EXISTS");
        }
    }
};
