<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Continuation of 000050 — `commission` also needs IDENTITY.
 * Discovered when scripts/commissions-recalc.php tried to insert a row
 * and Postgres rejected NULL id.
 *
 * Kept in a separate migration so the already-applied 000050 isn't
 * re-run. The check inside is idempotent — safe to re-run.
 */
return new class extends Migration
{
    public $withinTransaction = false;

    private array $tables = [
        'commission',
    ];

    public function up(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            $hasIdentity = DB::scalar(
                "SELECT count(*) FROM pg_attribute
                 WHERE attrelid = to_regclass('public.$quoted')
                   AND attname='id' AND attidentity <> ''"
            );
            if ($hasIdentity) continue;

            DB::statement("ALTER TABLE $quoted ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");

            $seqName = '"' . $t . '_id_seq"';
            $maxId = (int) DB::scalar("SELECT COALESCE(MAX(id), 0) FROM $quoted");
            $start = max(1, $maxId + 1);
            DB::statement("SELECT setval('$seqName', $start, false)");
        }
    }

    public function down(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            DB::statement("ALTER TABLE $quoted ALTER COLUMN id DROP IDENTITY IF EXISTS");
        }
    }
};
