<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Три поставщика, которых не было в counterparty, но их листы есть в
 * таблице импорта транзакций. Идемпотентно: если имя уже занято —
 * пропускаем.
 */
return new class extends Migration
{
    public $withinTransaction = false;

    private const SEED = [
        'Medlife',
        'Брокер+',
        'Private Equity',
    ];

    public function up(): void
    {
        // Counterparty — legacy Directual-таблица без IDENTITY на PK.
        // Добавляем IDENTITY идемпотентно (тот же паттерн, что 000050/060/090).
        $hasIdentity = DB::scalar(
            "SELECT count(*) FROM pg_attribute
             WHERE attrelid = 'counterparty'::regclass
               AND attname='id' AND attidentity <> ''"
        );
        if (! $hasIdentity) {
            DB::statement('ALTER TABLE counterparty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
            $max = (int) DB::scalar('SELECT COALESCE(MAX(id), 0) FROM counterparty');
            DB::statement("SELECT setval('counterparty_id_seq', " . max(1, $max + 1) . ', false)');
        }

        foreach (self::SEED as $name) {
            $exists = DB::table('counterparty')->where('counterpartyName', $name)->exists();
            if ($exists) continue;
            DB::table('counterparty')->insert(['counterpartyName' => $name]);
        }
    }

    public function down(): void
    {
        // No-op: удалять поставщика опасно, к нему могут привязаться транзакции.
    }
};
