<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Ещё одна legacy Directual-таблица без IDENTITY на PK. PoolRunner::persist()
 * падал на NOT NULL id при первом применении пула. Тот же паттерн, что в
 * 000050/000060 — добавляем GENERATED BY DEFAULT AS IDENTITY и выравниваем
 * sequence по MAX(id)+1. Идемпотентно.
 */
return new class extends Migration
{
    public $withinTransaction = false;

    private array $tables = ['poolLog'];

    public function up(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            $hasIdentity = DB::scalar(
                "SELECT count(*) FROM pg_attribute
                 WHERE attrelid = to_regclass('public.$quoted')
                   AND attname='id' AND attidentity <> ''"
            );
            if ($hasIdentity) continue;

            DB::statement("ALTER TABLE $quoted ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");

            $seqName = '"' . $t . '_id_seq"';
            $maxId = (int) DB::scalar("SELECT COALESCE(MAX(id), 0) FROM $quoted");
            $start = max(1, $maxId + 1);
            DB::statement("SELECT setval('$seqName', $start, false)");
        }
    }

    public function down(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            DB::statement("ALTER TABLE $quoted ALTER COLUMN id DROP IDENTITY IF EXISTS");
        }
    }
};
