<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Legacy tables from Directual have `id integer not null` with no sequence /
 * identity — ids were generated externally. Laravel's insertGetId() can't
 * supply an id and Postgres refuses the NULL. This broke
 * - volumeCalculator  (calculator history save)
 * - Contest           (contest create)
 * - other low-traffic legacy tables
 *
 * Add GENERATED BY DEFAULT AS IDENTITY and align the sequence to MAX(id)+1
 * so existing hard-coded ids keep working.
 */
return new class extends Migration
{
    public $withinTransaction = false;

    /**
     * All legacy tables that are actually written from Laravel today (or
     * about to be). Rest can be added later if/when they start being written.
     */
    private array $tables = [
        'volumeCalculator',
        'Contest',
    ];

    public function up(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            // Skip if identity already present (idempotent after a partial run).
            // Note: to_regclass must get the quoted name as a literal, not as
            // a parameter — PG lowercases the result of a parameter cast.
            $hasIdentity = DB::scalar(
                "SELECT count(*) FROM pg_attribute
                 WHERE attrelid = to_regclass('public.$quoted')
                   AND attname='id' AND attidentity <> ''"
            );
            if ($hasIdentity) continue;

            DB::statement("ALTER TABLE $quoted ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");

            // Align sequence. pg_get_serial_sequence() + setval() via a
            // parameter lower-cases the table name, so build the sequence
            // name explicitly instead.
            $seqName = '"' . $t . '_id_seq"';
            $maxId = (int) DB::scalar("SELECT COALESCE(MAX(id), 0) FROM $quoted");
            $start = max(1, $maxId + 1);
            DB::statement("SELECT setval('$seqName', $start, false)");
        }
    }

    public function down(): void
    {
        foreach ($this->tables as $t) {
            $quoted = '"' . $t . '"';
            DB::statement("ALTER TABLE $quoted ALTER COLUMN id DROP IDENTITY IF EXISTS");
        }
    }
};
